# OP LABEL
UNDEFINED_OP_LABEL = 0
HUMAN_OP_LABEL = 1
MACHINE_OP_LABEL = 2

# USER OP EVENT TYPE
MOUSE_DOWN_EVENT = 1
MOUSE_UP_EVENT = 2
MOUSE_MOVE_EVENT = 3
SCROLL_EVENT = 4
MOUSE_ENTER_EVENT = 5
MOUSE_LEAVE_EVENT = 6

# CAPTCHA TYPE
ENG_TEXT_TYPE = 0
CH_TEXT_TYPE = 1
TOP_PIC_TYPE = 2
SELECT_PIC_TYPE = 3
MOVE_CAPTCHA_TYPE = 10
CLICK_CAPTCHA_TYPE = 11




